# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drawtogether', '0002_loggedinuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SlugField(unique=True)),
                ('in_game', models.IntegerField(default=0)),
                ('target_word', models.CharField(max_length=50)),
                ('time_limit', models.IntegerField(default=60)),
                ('time_left', models.IntegerField(default=60)),
                ('win_a', models.IntegerField(default=0)),
                ('win_b', models.IntegerField(default=0)),
                ('total_turns', models.IntegerField(default=0)),
                ('turn_draw', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_draw', to=settings.AUTH_USER_MODEL)),
                ('turns_guess', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_guess', to=settings.AUTH_USER_MODEL)),
                ('user_a', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
