# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawtogether', '0003_game_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='turn_draw',
            new_name='turns_draw',
        ),
    ]
