# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawtogether', '0004_auto_20170423_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='turns_draw',
        ),
        migrations.RemoveField(
            model_name='game',
            name='turns_guess',
        ),
    ]
